export const SET_LOCATION = 'SET_LOCATION'
export const SET_FLAT_TYPE = 'SET_FLAT_TYPE'
export const SET_RECENT_SEARCH = 'SET_RECENT_SEARCH'
export const SET_SELECTED_LOCATION = 'SET_SELECTED_LOCATION'
export const SET_SEARCH_FOCUS = 'SET_SEARCH_FOCUS'
export const SET_SEARCH_BLUR = 'SET_SEARCH_BLUR'


